# -*- coding: utf-8 -*-
"""visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r8PZgE5ZM2GqT621OZ26IExJYz-6CuUf
"""



from google.colab import drive
drive.mount('/content/drive')

import kagglehub

# Download latest version
path = kagglehub.dataset_download("jaderz/hospital-beds-management")

print("Path to dataset files:", path)

import os

for f in os.listdir(path):
    print(f)

import pandas as pd
import os

file_path = os.path.join(path, "patients.csv")
df = pd.read_csv(file_path)

df.head()

import os

print("Dataset path:", path)
for f in os.listdir(path):
    print(f)

import os
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# ---- PATH ----
path = "/root/.cache/kagglehub/datasets/jaderz/hospital-beds-management/versions/1"

# ---- LOAD DATA ----
services_weekly = pd.read_csv(os.path.join(path, "services_weekly.csv"))
patients = pd.read_csv(os.path.join(path, "patients.csv"))
staff_schedule = pd.read_csv(os.path.join(path, "staff_schedule.csv"))
staff = pd.read_csv(os.path.join(path, "staff.csv"))

# -------------------------------------------------
# 1) WEEKLY DEMAND / ADMITTED / REFUSED (TIMELINE)
# -------------------------------------------------
# Toplam (tüm servisler) bazında: talep, kabul, reddedilen
weekly_agg = (
    services_weekly
    .groupby("week")[["patients_request", "patients_admitted", "patients_refused"]]
    .sum()
    .reset_index()
)

plt.figure(figsize=(10, 5))
plt.plot(weekly_agg["week"], weekly_agg["patients_request"], label="Patients Request")
plt.plot(weekly_agg["week"], weekly_agg["patients_admitted"], label="Patients Admitted")
plt.plot(weekly_agg["week"], weekly_agg["patients_refused"], label="Patients Refused")

plt.title("Weekly Patient Demand, Admissions and Refusals")
plt.xlabel("Week")
plt.ylabel("Number of Patients")
plt.legend()
plt.tight_layout()
plt.savefig("timeline_demand_admit_refuse.png", dpi=300)
plt.close()


# -------------------------------------------------
# 2) REFUSAL RATE HEATMAP (SERVICE × WEEK)
# -------------------------------------------------
heat_df = services_weekly.copy()
heat_df["refusal_rate"] = heat_df["patients_refused"] / heat_df["patients_request"]

heatpivot = heat_df.pivot(index="service", columns="week", values="refusal_rate")

plt.figure(figsize=(12, 6))
sns.heatmap(heatpivot, cmap="Reds", linewidths=0.5, annot=False)
plt.title("Refusal Rate per Service and Week")
plt.xlabel("Week")
plt.ylabel("Service")
plt.tight_layout()
plt.savefig("refusal_rate_heatmap.png", dpi=300)
plt.close()


# -------------------------------------------------
# 3) STAFF ALIGNMENT (AVAILABLE vs PRESENT)
# -------------------------------------------------
# Staff tablosu: her servis için toplam unique personel sayısı (potansiyel kapasite)
staff_available = staff.groupby("service")["staff_id"].nunique()

# Staff_schedule: present=1 olanları toplayıp haftalık ortalama "fiilen mevcut" personel
staff_present = (
    staff_schedule
    .groupby(["service", "week"])["present"]
    .sum()
    .groupby("service")
    .mean()
)

matrix = pd.concat([staff_available, staff_present], axis=1)
matrix.columns = ["Total Staff (Registered)", "Avg Staff Present per Week"]

plt.figure(figsize=(10, 5))
matrix.plot(kind="bar")
plt.title("Staff Alignment per Service")
plt.xlabel("Service")
plt.ylabel("Staff Count")
plt.tight_layout()
plt.savefig("staff_alignment.png", dpi=300)
plt.close()

print("Generated figures:")
print(" - timeline_demand_admit_refuse.png")
print(" - refusal_rate_heatmap.png")
print(" - staff_alignment.png")